CREATE TABLE IF NOT EXISTS products(
 id SERIAL PRIMARY KEY,name TEXT NOT NULL,price NUMERIC(12,2) NOT NULL DEFAULT 0,
 sizes TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],color TEXT NOT NULL DEFAULT '',
 description TEXT NOT NULL DEFAULT '',image_url TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS orders(
 id SERIAL PRIMARY KEY,customer_name TEXT NOT NULL,phone TEXT NOT NULL,product_name TEXT NOT NULL,
 size TEXT DEFAULT '',color TEXT DEFAULT '',quantity INTEGER DEFAULT 1,note TEXT DEFAULT '',created_at TIMESTAMPTZ DEFAULT NOW());
